id = "koto-zed"
name = "koto-zed"
description = "Support for Koto in Zed"
version = "0.0.1"
schema_version = 1
authors = ["Roberto Saccon"]
repository = "https://github.com/rsaccon/koto-zed"

[grammars.koto]
repository = "https://github.com/koto-lang/tree-sitter-koto"
commit = "e602222ba63a353c43700f6eb3bfd4b098878695"

[language_servers.koto_ls]
name = "koto-ls"
languages = ["Koto"]
