name = "Koto"
grammar = "koto"
path_suffixes = ["koto"]
line_comments = ["# "]
block_comment = ["#- ", " -#"]
brackets = [
    { start = "{", end = "}", close = true, newline = false },
    { start = "[", end = "]", close = true, newline = false },
    { start = "(", end = ")", close = true, newline = false },
    { start = "|", end = "|", close = true, newline = false },
    { start = "\"", end = "\"", close = true, newline = false },
    { start = "'", end = "'", close = true, newline = false },
]
autoclose_before = ")}]"
tab_size = 2
